apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: 
  name: 
  namespace: openshift-machine-api
spec:
  replicas: 01
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: 
      machine.openshift.io/cluster-api-machineset: 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: 
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          node.btb/servico: logging
      taints:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
      - key: 
        value: logging
        effect: NoSchedule
      providerSpec:
        value:
          apiVersion: 
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: V
          memoryMiB: 8192
          network:
            devices:
            - networkName:
          numCPUs: 16
          numCoresPerSocket: 2
          snapshot: ""
          template: 
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: 
            datastore: 
            folder: 
            resourcePool: 
            server: 