apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
  name: ovs-br-vmdata
spec:
  desiredState:
    interfaces:
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp: false
          port:
            - name: bond0
        description: |-
          Ponte OVS principal conectada ao bond0, 
          com STP habilitado, permitindo trunk de VLANs
          e integracao com o OVN-Kubernetes.
        name: br-vmdata
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: br-vmdata
          localnet: vmdata
          state: present